### Dependency

In [1]:
import math
import numpy as np
from scipy.stats import mode

### Root and Exponentiation 开根号/求平方

In [2]:
x=9
up=1/2
print(pow(x,up))

3.0


### Quartile 四分距

In [3]:
def quartile(Data):
    maximum = np.max(Data)
    minimum = np.min(Data)   
    Data.sort() # odd
    # median
    index=(int)(len(Data)/2)
    if (len(Data)%2) == 0:     
        median = (Data[index]+Data[index-1])/2
        leftdata = arr[:index]
        rightdata = arr[index:]
    else:       
        median = Data[index]
        leftdata = arr[:index+1] # including median
        rightdata = arr[index:]
    # Q1 
    leftindex=(int)(len(leftdata)/2)
    if(len(leftdata)%2) ==0:
        q1 = (leftdata[leftindex]+leftdata[leftindex-1])/2
    else:
        q1 = leftdata[leftindex]
    # Q3
    rightindex=(int)(len(rightdata)/2)
    if(len(leftdata)%2) ==0:
        q3 = (rightdata[rightindex]+rightdata[rightindex-1])/2
    else:
        q3 = rightdata[rightindex]
    # IQR
    IQR = q3-q1
    new_max= q3+1.5*IQR
    new_min= q1-1.5*IQR
    # Outlier
    outl1 = Data[Data<new_min]
    outl2 = Data[Data>new_max]
    if outl1.size>0 and outl2.size>0:
        outl = np.concatenate((outl1,outl2))
    elif outl1.size>0: 
        outl= outl1
    elif outl2.size>0: 
        outl= outl2
    else:
        outl= None
    return minimum,maximum,median,q1,q3,IQR,outl

In [4]:
arr = np.array([0,5,14,16,17,19,19,19,22,30,50])
mi,mx,m,q1,q3,iqr,outlier=quartile(arr)
md = mode(arr)[0][0]
print(' min:%f\n max:%f\n median:%f\n Q1:%f\n Q3:%f\n IQR:%f\n mode:%f\n' % (mi,mx,m,q1,q3,iqr,md))
print('outlier:',outlier)

 min:0.000000
 max:50.000000
 median:19.000000
 Q1:15.000000
 Q3:20.500000
 IQR:5.500000
 mode:19.000000

outlier: [ 0  5 30 50]


### Mean, Var 均值，方差

In [5]:
arr1=np.array([100,400,600,800,3000,4200])
print(' mean:%f\n var:%f\n' % (np.mean(arr1),np.var(arr1)))

 mean:1516.666667
 var:2334722.222222



### Binning 

In [6]:
arr2 = np.array([8,10,15,35,50,52,85,89,92,158,201,251])
bin_step=(np.max(arr2)-np.min(arr2))/3
print(np.min(arr2)+2*bin_step)

170.0


### Distance between tow points 两点or两vector（多维）间距

+ Manhattan distance 曼哈顿距离 r=1

In [7]:
def Manhat_dist(point1,point2):
    if len(point1)!=len(point2):
        return "bits not matching"
    temp=0
    for i in range(len(point1)):
        temp+=abs(point1[i]-point2[i])
   
    return temp

In [8]:
P1 =(1,0,1,0,1,1,0,0,0,1)
P2 =(1,0,0,0,1,1,1,0,0,0)
result=Manhat_dist(P1,P2)
print(result)

3


+ Euclidean distance 欧氏距离  r=2

In [9]:
def Euclid_dist(point1,point2):
    if len(point1)!=len(point2):
        return "bits not matching"
    
    temp=0
    for i in range(len(point1)):
        temp+=pow((point1[i]-point2[i]),2)
    
    return temp

In [10]:
# input two data points in the same dimension
P1 =(0,2)
P2 =(3,4)
result=Euclid_dist(P1,P2)
print("Before root:",result)  # before root
print("Number of distance is:",math.sqrt(result)) #  after root, real value

Before root: 13
Number of distance is: 3.605551275463989


In [11]:
training_0 = np.array([[0,1],
                      [0,0],
                      [1,1],
                       [0,1],
                       [1,0],
                       [0,0],
                       [1,1],
                       [0,0],
                       [1,0],
                       [1,0]
                      ])
training_0_label = np.array([1,2,1,1,1,2,1,2,1,2])
test_0 =np.array([[2/3,1/3],[2/3,1/3],[2/3,1/3],[2/3,1/3],[2/3,1/3],[2/3,1/3],[2/3,1/3],[2/3,1/3],[2/3,1/3],[2/3,1/3]])
result_0 = Euclid_dist(training_0,test_0)
print(result_0)

bits not matching


+ Chebyshev distance 切比雪夫距离

In [12]:
def Chebyshev_dist(point1,point2):
    if point1.size !=point2.size:
        return "bits not matching"
    return np.max(abs(point1-point2))

In [13]:
P1 =np.array([0,2])
P2 =np.array([3,4])
result=Chebyshev_dist(P1,P2)
print("Chebyshev distance:",result) 

Chebyshev distance: 3


### Jaccard & SM coefficients

In [14]:
def coef_calc(v1,v2):
    
    M01=0
    M10=0
    M00=0
    M11=0
    for i in range(P1.size):
        if P1[i]==0 and P2[i]==0:
            M00+=1
        elif P1[i]!=0 and P2[i]==0:
            M01+=1
        elif P1[i]==0 and P2[i]!=0:
            M10+=1 
        else:
            M11+=1
    
    SMC = (M11+M00)/(M01+M10+M11+M00)
    JA = (M11)/(M01+M10+M11)
    
    return JA,SMC

In [15]:
P1 =np.array([1,0,1,0,1,1,0,0,0,1])
P2 =np.array([1,0,0,0,1,1,1,0,0,0])
jac,smc=coef_calc(P1,P2)
print('Jaccard value:%f\n SM value:%f\n'%(jac,smc))

Jaccard value:0.500000
 SM value:0.700000



### Linear  equation calculation 线性方程计算

In [16]:
def linear_calculation(W,X,b):
    return ((np.dot(X, W.T))+b)

In [17]:
# W,X should be in the same dimensions
Wvector= np.array([(0.463,0.81,0.55)])   # input coefficients W 
Xvector= np.array([(-1.2,1.1,-0.4)])       # input variables X 
bias= -0.3                      # input bias
lin_result = linear_calculation(Wvector,Xvector,bias)
print("linear calcucating result is:",lin_result)

linear calcucating result is: [[-0.1846]]


### Sigmoid function

In [18]:
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [19]:
sigmoid_x= lin_result
sigmoid_result=sigmoid(sigmoid_x)
print("sigmoid result is:",sigmoid_result)

sigmoid result is: 0.45398061001404805


### Feature map of CNN by kernel 特征提取/卷积神经网络

In [20]:
def CNN_featureMap(kernel,data):
    
    column_loop=data.shape[1]-kernel.shape[1]+1 # 横向取卷积区域次数
    row_loop=data.shape[0]-kernel.shape[0]+1 # 换行次数
    outputMatrix = np.zeros([row_loop,column_loop])
    
    for i in range(row_loop):
        for j in range(column_loop):
            conv_area = data[i:(i+kernel.shape[0]),j:(j+kernel.shape[1])] 
            conv_result = np.sum(conv_area*kernel) # the sum of the star product
            outputMatrix[i,j]=conv_result           
    
    return outputMatrix

In [21]:
CNN_Kerner=np.array([[-1,2,-1],
                 [0,0,2],
                 [2,-1,1]])
inputMatrix=np.array([[0,1,0,1,1,0,1,0],
                     [1,0,1,0,0,1,1,0],
                     [0,1,0,1,1,0,0,1],
                     [1,0,0,0,1,0,1,1],
                     [1,0,0,1,1,0,0,0],
                     [0,1,0,0,0,1,1,0],     
                     [0,1,0,0,0,1,1,0],
                     [0,0,1,1,0,1,0,0]])
featureMap_result = CNN_featureMap(CNN_Kerner,inputMatrix)
print(featureMap_result)


[[ 3.  1.  1.  4.  2.  3.]
 [ 0.  4.  2. -2.  4.  3.]
 [ 4. -1.  3.  2.  3.  1.]
 [-2.  4.  1.  3. -2.  2.]
 [-2.  1.  1.  4.  1.  1.]
 [ 3. -1.  1.  4.  2.  3.]]


### Feature map pooling      CNN池化 

In [22]:
def CNN_maxPooling(scale,featureMap):
    
    row_slice=scale[0]  # stride
    column_slice=scale[1] # stride
    row=featureMap.shape[0] # map size
    column=featureMap.shape[1] # map size
    # loop times calculation
    loop_row1 = row/row_slice  
    loop_row2 = (int)(row/row_slice)
    loop_column1 = column/column_slice
    loop_column2 = (int)(column/column_slice) 
    if loop_row1>loop_row2:
        loop_row2+=1
    loop_row = loop_row2
    if loop_column1>loop_column2:
        loop_column2+=1
    loop_column = loop_column2
    
    #print(loop_row,loop_column) # result shape
    pooled_map = np.zeros([loop_row,loop_column])  # store max data
    for i in range(loop_row):
        for j in range(loop_column):
            if (i==loop_row-1): # --->most down side
                if (j==loop_column-1):  # --->most right side     
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):,(j*column_slice):]) # final one
                else:
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):,(j*column_slice):((j+1)*column_slice)]) # final row
            else:                
                if (j==loop_column-1):          
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):((i+1)*row_slice),(j*column_slice):]) # final column but not final row
                else:
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):((i+1)*row_slice),(j*column_slice):((j+1)*column_slice)]) # not final row/column
           
                
    return pooled_map
   

In [23]:
# parameter0: stride
CNN_maxPooling((2,2),featureMap_result)

array([[4., 4., 4.],
       [4., 3., 3.],
       [3., 4., 3.]])

### Update Weight，Perceptron      感知机权值更新

In [24]:
def Perceptron(W,X,y):
    
    classified_result = y * (np.sum(X*W))

    if classified_result <= 0:
        W = W + (y*X)
        return W,'wrong',classified_result
    else:
        return W,'right',classified_result

In [25]:
# data input by steps
W_ = np.array([0,1,0])

X_ = np.array([1,-0.5,-0.5])
y_ = -1

W_,Message,C_result=Perceptron(W_,X_,y_)
if Message=='wrong':
    print("Wrongly classfied, W should be updated to",W_ )
    print(C_result)
else:
    print("Right classfied, W should keep to",W_ )
    print(C_result)


Right classfied, W should keep to [0 1 0]
0.5


### Data Normalization 

+ min-max normalization

In [26]:
def maxminNor(x,MIN,MAX,MIN_new,MAX_new):
    return ((x-MIN)/(MAX-MIN))*(MAX_new-MIN_new)+MIN_new

In [27]:
Xvalue=arr1
MinValue=100
MaxValue=4200
MinValue_N=0
MaxValue_N=100
nor_result=maxminNor(Xvalue,MinValue,MaxValue,MinValue_N,MaxValue_N)
print("After min-max normalization, the result is",nor_result)

After min-max normalization, the result is [  0.           7.31707317  12.19512195  17.07317073  70.73170732
 100.        ]


+ Z-score

In [28]:
def Znor(Xset,Xpoint):
    x_bar = np.mean(Xset)
    std = np.std(Xset)
    return (Xpoint-x_bar)/std

def Znor_given(Xpoint,x_bar,std):
    return (Xpoint-x_bar)/std

In [29]:
Xset=np.array([-4,-2,0,2,4])
Xpoint=4
print(Znor(arr1,arr1))

[-0.92715014 -0.73081246 -0.59992068 -0.46902889  0.97078073  1.75613144]


+ Decimal normalization

In [30]:
def DecimalNor(x):
    negative=False
    if x<0:
        x=-x
        negative=True
    temp=x   # just for calculate the bit of number x
    count=1
    while (temp/10) > 1:
        temp=temp/10
        count=count+1
    
    if negative:
         return -x/pow(10,count)
    else:
        return x/pow(10,count)

In [31]:
Xvalue=4
print(DecimalNor(Xvalue))  # output should be in range [-1,1]

0.4


### Entropy calculation for Dicision tree  决策树-信息熵相关计算

+ I(h)=-log(p(h)),based on log2   ,h belongs to H
+ Entropy(S)=I(H)=Expectation(I(h1,h2,,,,hn)) = sum(-p(hi)I(hi))  
+ Gain(S,A)= Entropy(S)- Remainder(A)  
+ Remainder(A)= sum( Probability(k) * Entropy(k)) , k is the value of attribute A, sum all K in A

In [32]:
def Entropy(Ratio):  # Label Ratio 
    return np.sum(-Ratio*np.log2(Ratio))


def InformationGain(H ,value_Entropy,value_Prob):  
    '''
    H is the state entropy befor expanding this attribute;
    value_Entropy is the entropy in each value itself
    value_Prob is the propotion of each value in this attribute
    '''
    return H - np.sum(value_Prob * value_Entropy)

In [33]:
#### State Entropy
Ratios=np.array([3/8,5/8])# State entropy, label ratio. 1)填当前state的samples中各个labels的比例
H_S = Entropy(Ratios)
print("State entropy      H(S)=" ,H_S)

# Attribute Information Gain
Ratios_Value1=np.array([2/3,1/3])   # 2)在当前state的samples里，填节点中各个value对于各个labels的比例
Ratios_Value2=np.array([2/3,1/3])
Ratios_Value3=np.array([1/2,1/2]) # adjust by the num of kind of value in this attribute 

Value_Entropy = np.array([Entropy(Ratios_Value1),Entropy(Ratios_Value2),Entropy(Ratios_Value3)])  # 3) 修改value size
Value_Prob = np.array([3/8,3/8,2/8])  # 4) 在当前state的samples里，填各个value的比例,(value1,value2,value3)

Gain=InformationGain(H_S,Value_Entropy,Value_Prob)
print("InformationGain    Gain(S,A)=",Gain)

if True:  # Switch using Gain or GainRatio
    # Attribute GainRatio 
    H_A = Entropy(Value_Prob) 
    print("SplitInformation   H(A)=",H_A)
    print("Using in C.45      GainRatio(S,A)=",(Gain/H_A))

State entropy      H(S)= 0.954434002924965
InformationGain    Gain(S,A)= 0.015712127384097885
SplitInformation   H(A)= 1.561278124459133
Using in C.45      GainRatio(S,A)= 0.010063631288974199


+ Gini index
+ G(t)=1-sum((p(j|t))^2)  | node t, class j
+ G_split(a)= w1 * G(t1) + w2 * G(t2) | w1+w2=1 , the value lower , as split attribute better

In [34]:
def Gini(data):
    data = data/np.sum(data)
    return 1-np.sum(pow(data,2))
                    
def Gini_Split(g_Value,w_Label):
    return np.sum(g_Value * w_Label)

In [35]:
arr_gini =np.array([25,25]) # number of labels
print('Gini value is:',Gini(arr_gini))

Gini value is: 0.5


In [36]:
arr_gvalue = np.array([0,0.5])
arr_wLabel = np.array([0,50]) # number of labels
arr_wLabel = arr_wLabel/np.sum(arr_wLabel)
print('GiniSplit value is:',Gini_Split(arr_gvalue,arr_wLabel))

GiniSplit value is: 0.5


### xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

In [37]:
0.444-0.333

0.11099999999999999

In [38]:
0.209/(0.4*0.7*0.8*0.8+0.6*0.5*0.8*0.8+0.4*0.3*0.5*0.5+0.6*0.5*0.5*0.5)

0.4388912221755565

In [39]:
def Sum_positive(listX):
    SUM=0
    for i in listX:
        if i>0:
            SUM+=i
    return SUM
print(Sum_positive([1,2,3,7]))

13


In [40]:
a=[1,4]
b=(3,2,5)
a.append(b)
a.extend(b)
print(a)

[1, 4, (3, 2, 5), 3, 2, 5]


In [41]:
A = np.array([[2, 9],
            [4, 6],
             [6, 3]])
((A-np.mean(A))/np.std(A)).T @ ((A-np.mean(A))/np.std(A))
print((A-np.mean(A))/np.std(A))

[[-1.29903811  1.73205081]
 [-0.4330127   0.4330127 ]
 [ 0.4330127  -0.8660254 ]]
