### Dependency

In [1]:
import math
import numpy as np

### Distance between tow points 两点or两vector（多维）间距，欧氏距离

In [2]:
def D_twopoints(point1,point2):
    if len(point1)!=len(point2):
        return "bits not matching"
    
    temp=0
    for i in range(len(point1)):
        temp+=pow((point1[i]-point2[i]),2)
    
    return temp

In [3]:
P1 =(3.5,7)
P2 =(5,3)
result=D_twopoints(P1,P2)
print("Before root:",result)  # before root
print("Number of distance is:",math.sqrt(result)) #  after root, real value

Before root: 18.25
Number of distance is: 4.272001872658765


### Linear  equation calculation 线性方程计算

In [4]:
def linear_calculation(W,X,b):
    return ((np.dot(X, W.T))+b)

In [5]:
# W,X should be in the same dimensions
Wvector= np.array([(-1.2,1.1)])   # input coefficients W 
Xvector= np.array([(0.524979,0.880797)])       # input variables X 
bias= -0.3                       # input bias
lin_result = linear_calculation(Wvector,Xvector,bias)
print("linear calcucating result is:",lin_result)

linear calcucating result is: [[0.0389019]]


### Sigmoid function

In [6]:
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [7]:
sigmoid_x= lin_result
sigmoid_result=sigmoid(sigmoid_x)
print("sigmoid result is:",sigmoid_result)

sigmoid result is: 0.5097242486752799


### Feature map of CNN by kernel 特征提取/卷积神经网络

In [8]:
def CNN_featureMap(kernel,data):
    
    column_loop=data.shape[1]-kernel.shape[1]+1 # 横向取卷积区域次数
    row_loop=data.shape[0]-kernel.shape[0]+1 # 换行次数
    outputMatrix = np.zeros([row_loop,column_loop])
    
    for i in range(row_loop):
        for j in range(column_loop):
            conv_area = data[i:(i+kernel.shape[0]),j:(j+kernel.shape[1])] 
            conv_result = np.sum(conv_area*kernel) # the sum of the star product
            outputMatrix[i,j]=conv_result           
    
    return outputMatrix

In [9]:
CNN_Kerner=np.array([[-1,2,-1],
                 [0,0,2],
                 [2,-1,1]])
inputMatrix=np.array([[0,1,0,1,1,0,1,0],
                     [1,0,1,0,0,1,1,0],
                     [0,1,0,1,1,0,0,1],
                     [1,0,0,0,1,0,1,1],
                     [1,0,0,1,1,0,0,0],
                     [0,1,0,0,0,1,1,0],     
                     [0,1,0,0,0,1,1,0],
                     [0,0,1,1,0,1,0,0]])
featureMap_result = CNN_featureMap(CNN_Kerner,inputMatrix)
print(featureMap_result)


[[ 3.  1.  1.  4.  2.  3.]
 [ 0.  4.  2. -2.  4.  3.]
 [ 4. -1.  3.  2.  3.  1.]
 [-2.  4.  1.  3. -2.  2.]
 [-2.  1.  1.  4.  1.  1.]
 [ 3. -1.  1.  4.  2.  3.]]


### Feature map pooling      CNN池化 

In [10]:
def CNN_maxPooling(scale,featureMap):
    
    row_slice=scale[0]  # stride
    column_slice=scale[1] # stride
    row=featureMap.shape[0] # map size
    column=featureMap.shape[1] # map size
    # loop times calculation
    loop_row1 = row/row_slice  
    loop_row2 = (int)(row/row_slice)
    loop_column1 = column/column_slice
    loop_column2 = (int)(column/column_slice) 
    if loop_row1>loop_row2:
        loop_row2+=1
    loop_row = loop_row2
    if loop_column1>loop_column2:
        loop_column2+=1
    loop_column = loop_column2
    
    #print(loop_row,loop_column) # result shape
    pooled_map = np.zeros([loop_row,loop_column])  # store max data
    for i in range(loop_row):
        for j in range(loop_column):
            if (i==loop_row-1): # --->most down side
                if (j==loop_column-1):  # --->most right side     
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):,(j*column_slice):]) # final one
                else:
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):,(j*column_slice):((j+1)*column_slice)]) # final row
            else:                
                if (j==loop_column-1):          
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):((i+1)*row_slice),(j*column_slice):]) # final column but not final row
                else:
                    pooled_map[i,j]=np.max(featureMap[(i*row_slice):((i+1)*row_slice),(j*column_slice):((j+1)*column_slice)]) # not final row/column
           
                
    return pooled_map
   

In [11]:
# parameter0: stride
CNN_maxPooling((2,2),featureMap_result)

array([[4., 4., 4.],
       [4., 3., 3.],
       [3., 4., 3.]])